spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false'
    username: 'app_user'
    password: '@ppus3r'
  # JPA settings
  jpa:
    hibernate:
      ddl-auto: create-drop
