spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: 'app_user'
    password: '@ppus3r'
  # JPA settings
  jpa:
    hibernate:
      ddl-auto: create-drop
    # SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
